In [1]:
import os
os.chdir('./..')

In [2]:
import src.data as data
import pandas as pd
import numpy as np

In [3]:
speeds_train = data.speeds_train()
speeds_test = data.speeds_test()

caching speeds_train

speeds_train loaded in: 28.1751 s

shape of the dataframe is: (10832482, 9)
caching speeds_test

speeds_test loaded in: 5.9999 s

shape of the dataframe is: (3488814, 9)

In [4]:
sensors = data.sensors()

caching sensors

sensors loaded in: 0.0071 s

shape of the dataframe is: (2269, 5)

In [6]:
datetime_train = speeds_train.DATETIME_UTC.unique()
len(datetime_train)

8729

In [8]:
datetime_test = speeds_test.DATETIME_UTC.unique()
len(datetime_test)

3072

In [23]:
datetime_full = set(datetime_train)|set(datetime_test)
len(datetime_full)

11801

In [44]:
np.array(list(datetime_full))

array(['2018-11-15 20:45:00', '2018-12-15 17:45:00',
       '2018-11-02 00:30:00', ..., '2018-11-16 23:00:00',
       '2018-11-13 16:45:00', '2018-11-15 21:15:00'], dtype='<U19')

In [24]:
key_2_train = speeds_train.KEY_2.unique()
len(key_2_train)

1784

In [25]:
key_2_test = speeds_test.KEY_2.unique()
len(key_2_test)

1646

In [32]:
key_2_full = sorted(set(key_2_test)|set(key_2_train))
key_2_full

['0_333',
 '0_337',
 '0_342',
 '0_343',
 '0_357',
 '0_385',
 '0_407',
 '0_411',
 '0_423',
 '0_443',
 '0_454',
 '0_488',
 '0_520',
 '100_577',
 '101_1423',
 '102_837',
 '102_877',
 '102_918',
 '102_933',
 '102_949',
 '103_1051',
 '103_1067',
 '103_1082',
 '103_1123',
 '103_1163',
 '104_719',
 '104_749',
 '105_1251',
 '105_1281',
 '106_190',
 '107_1810',
 '108_108',
 '108_148',
 '108_175',
 '108_210',
 '108_253',
 '109_1747',
 '109_1790',
 '109_1825',
 '109_1852',
 '109_1892',
 '10_79',
 '110_613',
 '110_661',
 '111_1339',
 '111_1387',
 '112_590',
 '112_610',
 '112_644',
 '113_1356',
 '113_1390',
 '113_1410',
 '114_175',
 '114_215',
 '114_229',
 '114_272',
 '114_297',
 '114_308',
 '114_327',
 '114_346',
 '114_358',
 '114_377',
 '115_1623',
 '115_1642',
 '115_1654',
 '115_1673',
 '115_1692',
 '115_1703',
 '115_1728',
 '115_1771',
 '115_1785',
 '115_1825',
 '116_224',
 '116_241',
 '117_1759',
 '117_1776',
 '118_398',
 '118_422',
 '118_428',
 '118_488',
 '118_537',
 '118_578',
 '118_604',
 '119_1396',
 '119_1422',
 '119_1463',
 '119_1512',
 '119_1572',
 '119_1578',
 '119_1602',
 '11_1921',
 '120_127',
 '121_1873',
 '122_567',
 '122_590',
 '122_604',
 '122_610',
 '122_660',
 '122_668',
 '122_669',
 '122_679',
 '122_680',
 '122_701',
 '123_1299',
 '123_1320',
 '123_1321',
 '123_1331',
 '123_1332',
 '123_1340',
 '123_1390',
 '123_1396',
 '123_1410',
 '123_1433',
 '124_735',
 '125_1265',
 '126_74',
 '127_1926',
 '128_599',
 '129_1401',
 '12_50',
 '130_667',
 '130_870',
 '131_1130',
 '131_1333',
 '132_655',
 '132_675',
 '133_1325',
 '133_1345',
 '134_108',
 '134_130',
 '134_226',
 '134_75',
 '134_85',
 '135_1774',
 '135_1870',
 '135_1892',
 '135_1915',
 '135_1925',
 '136_226',
 '137_1774',
 '138_513',
 '138_533',
 '139_1467',
 '139_1487',
 '13_1950',
 '140_584',
 '140_592',
 '141_1408',
 '141_1416',
 '142_462',
 '142_503',
 '143_1497',
 '143_1538',
 '143_1558',
 '144_813',
 '145_1187',
 '146_1050',
 '146_1074',
 '146_1095',
 '146_1118',
 '146_1174',
 '146_1186',
 '146_1194',
 '146_1250',
 '146_1366',
 '146_1401',
 '146_1445',
 '146_1473',
 '146_1488',
 '146_1494',
 '146_1497',
 '146_1504',
 '146_1549',
 '146_1612',
 '146_1613',
 '146_1656',
 '146_1657',
 '146_1660',
 '146_1679',
 '146_811',
 '146_876',
 '146_904',
 '146_919',
 '146_925',
 '146_939',
 '146_990',
 '146_997',
 '147_1003',
 '147_1010',
 '147_1061',
 '147_1075',
 '147_1081',
 '147_1096',
 '147_1124',
 '147_1189',
 '147_321',
 '147_340',
 '147_343',
 '147_344',
 '147_387',
 '147_388',
 '147_451',
 '147_496',
 '147_503',
 '147_506',
 '147_512',
 '147_527',
 '147_555',
 '147_599',
 '147_634',
 '147_674',
 '147_750',
 '147_806',
 '147_814',
 '147_826',
 '147_905',
 '147_926',
 '147_950',
 '148_487',
 '148_499',
 '149_1501',
 '149_1513',
 '14_1045',
 '14_1070',
 '14_1073',
 '14_1100',
 '14_1102',
 '14_1127',
 '14_1145',
 '14_1177',
 '14_1239',
 '14_1282',
 '14_845',
 '14_901',
 '14_923',
 '14_956',
 '14_973',
 '150_626',
 '150_638',
 '150_645',
 '150_669',
 '150_670',
 '151_1330',
 '151_1331',
 '151_1355',
 '151_1362',
 '151_1374',
 '152_955',
 '153_1045',
 '154_471',
 '154_504',
 '155_1496',
 '155_1529',
 '156_384',
 '157_1616',
 '158_324',
 '158_337',
 '158_374',
 '158_382',
 '158_412',
 '158_425',
 '158_481',
 '158_519',
 '158_600',
 '158_639',
 '158_653',
 '159_1347',
 '159_1361',
 '159_1400',
 '159_1481',
 '159_1519',
 '159_1575',
 '159_1588',
 '159_1618',
 '159_1626',
 '159_1663',
 '159_1676',
 '15_1027',
 '15_1044',
 '15_1077',
 '15_1099',
 '15_1155',
 '15_718',
 '15_761',
 '15_823',
 '15_855',
 '15_873',
 '15_898',
 '15_900',
 '15_927',
 '15_930',
 '15_955',
 '160_263',
 '161_1737',
 '162_314',
 '163_1686',
 '164_187',
 '164_196',
 '164_204',
 '164_207',
 '164_246',
 '164_256',
 '164_264',
 '165_1736',
 '165_1744',
 '165_1754',
 '165_1793',
 '165_1796',
 '165_1804',
 '165_1813',
 '166_716',
 '166_768',
 '166_778',
 '167_1222',
 '167_1232',
 '167_1284',
 '168_809',
 '169_1191',
 '16_549',
 '16_555',
 '16_556',
 '16_562',
 '16_569',
 '16_573',
 '16_576',
 '16_581',
 '16_585',
 '16_588',
 '16_590',
 '16_591',
 '16_597',
 '16_601',
 '16_605',
 '16_607',
 '16_612',
 '16_615',
 '170_255',
 '170_279',
 '170_303',
 '171_1697',
 '171_1721',
 '171_1745',
 '172_102',
 '172_110',
 '172_122',
 '172_137',
 '172_150',
 '172_166',
 '172_178',
 '172_217',
 '172_227',
 '173_1773',
 '173_1783',
 '173_1822',
 '173_1834',
 '173_1850',
 '173_1863',
 '173_1878',
 '173_1890',
 '173_1898',
 '174_598',
 '175_1402',
 '176_310',
 '176_363',
 '176_367',
 '177_1633',
 '177_1637',
 '177_1690',
 '178_1015',
 '178_1042',
 '178_1097',
 '178_1110',
 '178_1133',
 '178_1141',
 '178_1168',
 '178_1189',
 '178_1240',
 '178_1254',
 '178_1283',
 '178_1286',
 '178_1295',
 '178_1306',
 '178_1324',
 '178_874',
 '178_894',
 '178_903',
 '178_907',
 '178_961',
 '179_1093',
 '179_1097',
 '179_1106',
 '179_1126',
 '179_676',
 '179_694',
 '179_705',
 '179_714',
 '179_717',
 '179_746',
 '179_760',
 '179_811',
 '179_832',
 '179_859',
 '179_867',
 '179_890',
 '179_903',
 '179_958',
 '179_985',
 '17_1385',
 '17_1388',
 '17_1393',
 '17_1395',
 '17_1399',
 '17_1403',
 '17_1409',
 '17_1410',
 '17_1412',
 '17_1415',
 '17_1419',
 '17_1424',
 '17_1427',
 '17_1431',
 '17_1438',
 '17_1444',
 '17_1445',
 '17_1451',
 '180_513',
 '180_524',
 '180_541',
 '180_546',
 '180_571',
 '181_1429',
 '181_1454',
 '181_1459',
 '181_1476',
 '181_1487',
 '182_917',
 '183_1083',
 '184_365',
 '184_389',
 '184_418',
 '185_1582',
 '185_1611',
 '185_1635',
 '186_747',
 '187_1253',
 '188_481',
 '188_494',
 '188_511',
 '188_528',
 '188_551',
 '188_559',
 '189_1441',
 '189_1449',
 '189_1472',
 '189_1489',
 '189_1506',
 '189_1519',
 '18_101',
 '18_105',
 '18_109',
 '18_110',
 '190_382',
 '191_1618',
 '192_626',
 '193_1374',
 '194_106',
 '195_1894',
 '196_129',
 '197_1871',
 '198_527',
 '198_546',
 '198_553',
 '198_576',
 '199_1424',
 '199_1447',
 '199_1454',
 '199_1473',
 '19_1890',
 '19_1895',
 '19_1899',
 '1_1480',
 '1_1512',
 '1_1546',
 '1_1557',
 '1_1577',
 '1_1589',
 '1_1593',
 '1_1615',
 '1_1643',
 '1_1657',
 '1_1658',
 '1_1663',
 '1_1667',
 '200_442',
 '201_1558',
 '202_592',
 '202_601',
 '202_621',
 '202_627',
 '202_640',
 '203_1360',
 '203_1373',
 '203_1379',
 '203_1399',
 '203_1408',
 '204_114',
 '204_137',
 '204_211',
 '204_228',
 '204_246',
 '204_267',
 '204_307',
 '204_348',
 '204_404',
 '204_439',
 '204_485',
 '204_524',
 '204_550',
 '204_577',
 '204_593',
 '204_644',
 '204_709',
 '204_735',
 '204_751',
 '205_1249',
 '205_1265',
 '205_1291',
 '205_1356',
 '205_1407',
 '205_1423',
 '205_1450',
 '205_1476',
 '205_1515',
 '205_1561',
 '205_1596',
 '205_1652',
 '205_1693',
 '205_1733',
 '205_1754',
 '205_1772',
 '205_1789',
 '205_1863',
 '205_1886',
 '206_174',
 '207_1826',
 '208_777',
 '209_164',
 '20_375',
 '210_1836',
 '211_446',
 '211_493',
 '212_1507',
 '212_1554',
 '213_511',
 '213_547',
 '213_559',
 '213_594',
 '214_1406',
 '214_1441',
 '214_1453',
 '214_1489',
 '215_468',
 '216_1532',
 '217_1011',
 '217_959',
 '218_1041',
 '218_989',
 '219_44',
 '219_73',
 '21_616',
 '220_1927',
 '220_1956',
 '221_1006',
 '221_1016',
 '221_1042',
 '221_996',
 '222_1004',
 '222_958',
 '222_984',
 '222_994',
 '223_1251',
 '224_160',
 '225_1840',
 '226_802',
 '226_808',
 '226_818',
 '226_838',
 '226_850',
 '227_1150',
 '227_1162',
 '227_1182',
 '227_1192',
 '227_1198',
 '228_587',
 '229_1413',
 '22_1384',
 '230_830',
 '231_1170',
 '232_896',
 '233_1104',
 '234_597',
 '234_615',
 '234_638',
 '234_663',
 '234_696',
 '234_714',
 '235_1286',
 '235_1304',
 '235_1337',
 '235_1362',
 '235_1385',
 '235_1403',
 '236_332',
 '236_360',
 '236_370',
 '237_1630',
 '237_1640',
 '237_1668',
 '238_356',
 '238_384',
 '239_1616',
 '239_1644',
 '23_66',
 '240_712',
 '240_714',
 '240_749',
 '241_1251',
 '241_1286',
 '241_1288',
 '242_846',
 '243_1154',
 '244_622',
 '244_624',
 '244_638',
 '245_1362',
 '245_1376',
 '245_1378',
 '246_508',
 '246_516',
 '246_530',
 '246_544',
 '246_550',
 '246_557',
 '247_1443',
 '247_1450',
 '247_1456',
 '247_1470',
 '247_1484',
 '247_1492',
 '248_599',
 '249_1401',
 '24_1934',
 '250_821',
 '250_849',
 '251_1151',
 '251_1179',
 '252_491',
 '253_1509',
 '254_103',
 '254_110',
 '254_72',
 '255_1890',
 '255_1897',
 '255_1928',
 '256_861',
 '257_1139',
 '258_107',
 '258_142',
 '259_1858',
 '259_1893',
 '25_931',
 '260_972',
 '261_1028',
 '262_381',
 '262_406',
 '262_417',
 '262_477',
 '263_1583',
 '263_1594',
 '263_1619',
 '264_287',
 '264_313',
 '265_1687',
 '265_1713',
 '266_498',
 '266_566',
 '267_1434',
 '267_1502',
 '268_719',
 '269_1281',
 '26_1069',
 '270_688',
 '271_1312',
 '272_65',
 '272_78',
 '273_1922',
 '273_1935',
 '274_780',
 '274_834',
 '275_1166',
 '275_1220',
 '276_754',
 '277_1246',
 '278_686',
 '279_1314',
 '27_527',
 '27_545',
 '280_617',
 '281_1383',
 '282_374',
 '282_443',
 '283_1557',
 '283_1626',
 '284_744',
 '285_1256',
 '286_854',
 '287_1146',
 '288_524',
 '289_1476',
 '28_1455',
 '28_1473',
 '290_299',
 '291_1701',
 '292_743',
 '292_761',
 '292_767',
 '292_768',
 '292_775',
 '292_776',
 '292_782',
 '292_789',
 '292_792',
 '293_1208',
 '293_1211',
 '293_1218',
 '293_1224',
 '293_1225',
 '293_1232',
 '293_1233',
 '293_1239',
 '293_1257',
 '294_400',
 '294_422',
 '294_459',
 '295_1541',
 '295_1578',
 '295_1600',
 '296_916',
 '296_950',
 '297_1050',
 '297_1084',
 '298_366',
 '298_395',
 '298_408',
 '299_1592',
 '299_1605',
 '299_1634',
 '29_275',
 '2_971',
 '2_974',
 '300_47',
 '301_1953',
 '302_996',
 '303_1004',
 '304_500',
 '305_1500',
 '306_371',
 '306_539',
 '307_1461',
 '307_1629',
 '308_175',
 '309_1825',
 '30_1725',
 '310_628',
 '311_1372',
 '312_155',
 '313_1845',
 '314_717',
 '314_764',
 '315_1236',
 '315_1283',
 '316_72',
 '317_1928',
 '318_228',
 '318_250',
 '319_1750',
 '319_1772',
 '31_47',
 '31_87',
 '320_827',
 '321_1173',
 '322_514',
 '323_1486',
 '324_218',
 '324_221',
 '324_249',
 '325_1751',
 '325_1779',
 '325_1782',
 '326_301',
 '326_327',
 '326_363',
 '326_368',
 '326_385',
 '326_412',
 '326_437',
 '326_486',
 '326_506',
 '327_1494',
 '327_1514',
 '327_1563',
 '327_1588',
 '327_1615',
 '327_1632',
 '327_1637',
 '327_1673',
 '327_1699',
 '328_787',
 '329_1213',
 '32_1913',
 '32_1953',
 '330_280',
 '330_284',
 '331_1720',
 '332_424',
 '333_1576',
 '334_415',
 '334_461',
 '334_483',
 '334_500',
 '335_1500',
 '335_1517',
 '335_1539',
 '335_1585',
 '336_939',
 '337_1061',
 '338_893',
 '338_930',
 '339_1070',
 '339_1107',
 '33_93',
 '340_89',
 '341_1911',
 '342_196',
 '343_1804',
 '344_538',
 '344_561',
 '344_589',
 '344_629',
 '345_1371',
 '345_1411',
 '345_1439',
 '345_1462',
 '346_463',
 '347_1537',
 '348_430',
 '349_1570',
 '34_1907',
 '350_575',
 '351_1425',
 '352_311',
 '352_398',
 '352_416',
 '353_1584',
 '353_1602',
 '353_1689',
 '354_960',
 '355_145',
 '356_1855',
 '357_878',
 '358_1122',
 '359_443',
 '359_464',
 '359_484',
 '35_467',
 '360_1516',
 '360_1536',
 '360_1557',
 '361_896',
 '362_1104',
 '363_150',
 '363_167',
 '363_190',
 '363_218',
 '363_229',
 '363_242',
 '363_265',
 '363_287',
 '363_305',
 '364_1695',
 '364_1713',
 '364_1735',
 '364_1758',
 '364_1771',
 '364_1782',
 '364_1810',
 '364_1833',
 '364_1850',
 '365_287',
 '365_301',
 '366_1699',
 '366_1713',
 '367_738',
 '368_1262',
 '369_386',
 '369_402',
 '369_404',
 '36_1533',
 '370_1596',
 '370_1598',
 '370_1614',
 '371_719',
 '372_1281',
 '373_427',
 '373_472',
 '373_481',
 '373_504',
 '373_521',
 '373_537',
 '374_1463',
 '374_1479',
 '374_1496',
 '374_1519',
 '374_1528',
 '374_1573',
 '375_914',
 '376_1086',
 '377_996',
 '378_1004',
 '379_453',
 '379_468',
 '379_474',
 '379_490',
 '37_432',
 '37_442',
 '37_448',
 '380_1510',
 '380_1526',
 '380_1532',
 '380_1547',
 '381_266',
 '382_1734',
 '383_86',
 '383_91',
 '384_1909',
 '384_1914',
 '385_198',
 '386_1802',
 '387_161',
 '388_1839',
 '389_169',
 '38_1552',
 '38_1558',
 '38_1568',
 '390_1831',
 '391_688',
 '392_1312',
 '393_244',
 '393_257',
 '393_341',
 '394_1659',
 '394_1743',
 '394_1756',
 '395_17',
 '395_26',
 '396_1974',
 '396_1983',
 '397_498',
 '398_1502',
 '399_251',
 '39_72',
 '3_1026',
 '3_1029',
 '400_1749',
 '401_859',
 '402_1141',
 '403_611',
 '404_1389',
 '405_191',
 '406_1809',
 '407_295',
 '408_1705',
 '409_321',
 '40_1928',
 '410_1679',
 '411_111',
 '411_73',
 '412_1889',
 '412_1927',
 '413_698',
 '414_1302',
 '415_165',
 '416_1835',
 '417_549',
 '417_565',
 '418_1435',
 '418_1451',
 '419_381',
 '419_394',
 '41_253',
 ...]

In [51]:
temp = pd.DataFrame(list(map(lambda x: x.split('_'), key_2_full)), columns = ['KEY', 'KM'])

In [52]:
temp['dummy']=0

In [54]:
datetime_df=pd.DataFrame(np.array(list(datetime_full)), columns=['DATETIME_UTC'])

In [55]:
datetime_df['dummy']=0

In [57]:
base_structure = pd.merge(datetime_df, temp).drop(['dummy'], axis=1)

In [58]:
base_structure

                 DATETIME_UTC  KEY    KM
0         2018-11-15 20:45:00    0   333
1         2018-11-15 20:45:00    0   337
2         2018-11-15 20:45:00    0   342
3         2018-11-15 20:45:00    0   343
4         2018-11-15 20:45:00    0   357
5         2018-11-15 20:45:00    0   385
6         2018-11-15 20:45:00    0   407
7         2018-11-15 20:45:00    0   411
8         2018-11-15 20:45:00    0   423
9         2018-11-15 20:45:00    0   443
10        2018-11-15 20:45:00    0   454
11        2018-11-15 20:45:00    0   488
12        2018-11-15 20:45:00    0   520
13        2018-11-15 20:45:00  100   577
14        2018-11-15 20:45:00  101  1423
15        2018-11-15 20:45:00  102   837
16        2018-11-15 20:45:00  102   877
17        2018-11-15 20:45:00  102   918
18        2018-11-15 20:45:00  102   933
19        2018-11-15 20:45:00  102   949
20        2018-11-15 20:45:00  103  1051
21        2018-11-15 20:45:00  103  1067
22        2018-11-15 20:45:00  103  1082
23        2018-11-15 20:45:00  103  1123
24        2018-11-15 20:45:00  103  1163
25        2018-11-15 20:45:00  104   719
26        2018-11-15 20:45:00  104   749
27        2018-11-15 20:45:00  105  1251
28        2018-11-15 20:45:00  105  1281
29        2018-11-15 20:45:00  106   190
...                       ...  ...   ...
21182765  2018-11-15 21:15:00   91  1778
21182766  2018-11-15 21:15:00   91  1800
21182767  2018-11-15 21:15:00   91  1815
21182768  2018-11-15 21:15:00   91  1826
21182769  2018-11-15 21:15:00   92   561
21182770  2018-11-15 21:15:00   93  1439
21182771  2018-11-15 21:15:00   94   123
21182772  2018-11-15 21:15:00   94   128
21182773  2018-11-15 21:15:00   94   156
21182774  2018-11-15 21:15:00   95  1844
21182775  2018-11-15 21:15:00   95  1872
21182776  2018-11-15 21:15:00   95  1877
21182777  2018-11-15 21:15:00   96   611
21182778  2018-11-15 21:15:00   96   671
21182779  2018-11-15 21:15:00   96   678
21182780  2018-11-15 21:15:00   96   697
21182781  2018-11-15 21:15:00   97  1303
21182782  2018-11-15 21:15:00   97  1322
21182783  2018-11-15 21:15:00   97  1329
21182784  2018-11-15 21:15:00   97  1389
21182785  2018-11-15 21:15:00   98   413
21182786  2018-11-15 21:15:00   98   458
21182787  2018-11-15 21:15:00   98   532
21182788  2018-11-15 21:15:00   98   624
21182789  2018-11-15 21:15:00   99  1376
21182790  2018-11-15 21:15:00   99  1468
21182791  2018-11-15 21:15:00   99  1542
21182792  2018-11-15 21:15:00   99  1587
21182793  2018-11-15 21:15:00    9  1559
21182794  2018-11-15 21:15:00    9  1583

[21182795 rows x 3 columns]

In [59]:
len(base_structure)

21182795

In [63]:
km_series = base_structure.pop('KM')
datetime_series = base_structure.pop('DATETIME_UTC')

base_structure['DATETIME_UTC']=datetime_series
base_structure['KM']=km_series
base_structure=base_structure.sort_values(['KEY', 'DATETIME_UTC', 'KM']).reset_index(drop=True)

In [64]:
base_structure

         KEY         DATETIME_UTC    KM
0          0  2018-09-01 00:00:00   333
1          0  2018-09-01 00:00:00   337
2          0  2018-09-01 00:00:00   342
3          0  2018-09-01 00:00:00   343
4          0  2018-09-01 00:00:00   357
5          0  2018-09-01 00:00:00   385
6          0  2018-09-01 00:00:00   407
7          0  2018-09-01 00:00:00   411
8          0  2018-09-01 00:00:00   423
9          0  2018-09-01 00:00:00   443
10         0  2018-09-01 00:00:00   454
11         0  2018-09-01 00:00:00   488
12         0  2018-09-01 00:00:00   520
13         0  2018-09-01 00:15:00   333
14         0  2018-09-01 00:15:00   337
15         0  2018-09-01 00:15:00   342
16         0  2018-09-01 00:15:00   343
17         0  2018-09-01 00:15:00   357
18         0  2018-09-01 00:15:00   385
19         0  2018-09-01 00:15:00   407
20         0  2018-09-01 00:15:00   411
21         0  2018-09-01 00:15:00   423
22         0  2018-09-01 00:15:00   443
23         0  2018-09-01 00:15:00   454
24         0  2018-09-01 00:15:00   488
25         0  2018-09-01 00:15:00   520
26         0  2018-09-01 00:30:00   333
27         0  2018-09-01 00:30:00   337
28         0  2018-09-01 00:30:00   342
29         0  2018-09-01 00:30:00   343
...       ..                  ...   ...
21182765  99  2019-01-01 22:00:00  1542
21182766  99  2019-01-01 22:00:00  1587
21182767  99  2019-01-01 22:15:00  1376
21182768  99  2019-01-01 22:15:00  1468
21182769  99  2019-01-01 22:15:00  1542
21182770  99  2019-01-01 22:15:00  1587
21182771  99  2019-01-01 22:30:00  1376
21182772  99  2019-01-01 22:30:00  1468
21182773  99  2019-01-01 22:30:00  1542
21182774  99  2019-01-01 22:30:00  1587
21182775  99  2019-01-01 22:45:00  1376
21182776  99  2019-01-01 22:45:00  1468
21182777  99  2019-01-01 22:45:00  1542
21182778  99  2019-01-01 22:45:00  1587
21182779  99  2019-01-01 23:00:00  1376
21182780  99  2019-01-01 23:00:00  1468
21182781  99  2019-01-01 23:00:00  1542
21182782  99  2019-01-01 23:00:00  1587
21182783  99  2019-01-01 23:15:00  1376
21182784  99  2019-01-01 23:15:00  1468
21182785  99  2019-01-01 23:15:00  1542
21182786  99  2019-01-01 23:15:00  1587
21182787  99  2019-01-01 23:30:00  1376
21182788  99  2019-01-01 23:30:00  1468
21182789  99  2019-01-01 23:30:00  1542
21182790  99  2019-01-01 23:30:00  1587
21182791  99  2019-01-01 23:45:00  1376
21182792  99  2019-01-01 23:45:00  1468
21182793  99  2019-01-01 23:45:00  1542
21182794  99  2019-01-01 23:45:00  1587

[21182795 rows x 3 columns]

In [65]:
%timeit base_structure[base_structure.KEY==100]

1.26 s ± 5.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)