In [1]:
import os
import sys
sys.path.append(os.chdir('../../'))

import pandas as pd
from tqdm.auto import tqdm
import numpy as np
import datetime

tqdm.pandas()
pd.options.display.max_columns = None
pd.options.display.max_colwidth = -1

import src.preprocessing.events as prepevents
import src.data as data
import src.utility as utility

In [3]:
X, Y = data.dataset('local','train', onehot=False)

caching resources/dataset/preprocessed/local/train/merged_dataset.csv.gz

In [20]:
X.shape

(15174, 45)

In [25]:
X.head()

,EMERGENCY_LANE,LANES,ROAD_TYPE,EVENT_DETAIL,EVENT_TYPE,SPEED_AVG_-4,SPEED_AVG_-3,SPEED_AVG_-2,SPEED_AVG_-1,SPEED_SD_-4,SPEED_SD_-3,SPEED_SD_-2,SPEED_SD_-1,SPEED_MAX_-4,SPEED_MAX_-3,SPEED_MAX_-2,SPEED_MAX_-1,SPEED_MIN_-4,SPEED_MIN_-3,SPEED_MIN_-2,SPEED_MIN_-1,N_VEHICLES_-4,N_VEHICLES_-3,N_VEHICLES_-2,N_VEHICLES_-1,WEATHER_-4,WEATHER_-3,WEATHER_-2,WEATHER_-1,DISTANCE_-4,DISTANCE_-3,DISTANCE_-2,DISTANCE_-1,TEMPERATURE_-4,TEMPERATURE_-3,TEMPERATURE_-2,TEMPERATURE_-1,MIN_TEMPERATURE_-4,MIN_TEMPERATURE_-3,MIN_TEMPERATURE_-2,MIN_TEMPERATURE_-1,MAX_TEMPERATURE_-4,MAX_TEMPERATURE_-3,MAX_TEMPERATURE_-2,MAX_TEMPERATURE_-1
13521,1,3,1,25,Calamita_naturale,192.542000,194.874930,202.720691,209.910442,22.065426,24.318307,26.689550,32.450898,241.082,257.262,275.060,334.926,142.384,135.912,105.170,134.294,104.0,86.0,110.0,113.0,Temporale con Debole Pioggia,Temporale con Debole Pioggia,Nelle Vicinanze Tempesta di Polvere,Nelle Vicinanze Tempesta di Polvere,8.0,8.0,8.0,8.0,21.0,21.0,20.0,20.0,21.0,21.0,20.0,20.0,21.0,21.0,21.0,21.0
13520,1,3,1,25,Calamita_naturale,209.130758,208.298598,217.809767,210.991694,25.556651,27.561915,36.304735,33.106265,273.442,284.768,351.106,362.432,160.182,147.238,148.856,139.148,95.0,107.0,120.0,144.0,Temporale con Debole Pioggia,Temporale con Debole Pioggia,Nelle Vicinanze Tempesta di Polvere,Nelle Vicinanze Tempesta di Polvere,11.0,11.0,11.0,11.0,21.0,21.0,20.0,20.0,21.0,21.0,20.0,20.0,21.0,21.0,21.0,21.0
13518,1,3,1,25,Calamita_naturale,225.828336,228.500916,240.609487,222.647128,32.376195,28.204935,35.581341,27.455518,343.016,309.038,375.376,304.184,135.912,181.216,182.834,176.362,131.0,107.0,113.0,94.0,Quasi Sereno,Quasi Sereno,Quasi Sereno,Quasi Sereno,12.0,12.0,12.0,12.0,24.0,24.0,24.0,24.0,18.0,18.0,18.0,18.0,29.0,29.0,29.0,29.0
13517,1,3,1,25,Calamita_naturale,232.146227,224.852970,237.067722,230.236344,33.998785,43.088621,26.967323,29.925787,310.656,315.510,339.780,347.870,74.428,84.136,177.980,177.980,88.0,66.0,79.0,64.0,Quasi Sereno,Quasi Sereno,Quasi Sereno,Quasi Sereno,12.0,12.0,12.0,12.0,24.0,24.0,24.0,24.0,18.0,18.0,18.0,18.0,29.0,29.0,29.0,29.0
13516,1,3,1,25,Calamita_naturale,196.560903,192.498270,192.767767,200.799379,27.821041,23.839163,38.689814,19.446529,273.442,252.408,270.206,245.936,147.238,148.856,92.226,166.654,31.0,37.0,43.0,29.0,Quasi Sereno,Quasi Sereno,Quasi Sereno,Quasi Sereno,15.0,15.0,15.0,15.0,24.0,24.0,24.0,24.0,18.0,18.0,18.0,18.0,29.0,29.0,29.0,29.0

In [23]:
mask_not_all_null = np.any(X[['SPEED_AVG_-4','SPEED_AVG_-3','SPEED_AVG_-2','SPEED_AVG_-1']].notnull(),axis=1)
X = X[mask_not_all_null]
Y = Y[mask_not_all_null]

In [24]:
X.iloc[518,25]

'Quasi Sereno'

## Speeds

#### Original

In [2]:
print(data.speeds_original('train').shape)
print(data.speeds_original('test').shape)
print()
print(data.speeds_original('train').shape)
print(data.speeds_original('test').shape)

caching resources/dataset/originals/speeds_train.csv.gz
(10832482, 9)
caching resources/dataset/originals/speeds_test.csv.gz
(3488814, 9)

(10832482, 9)
(3488814, 9)

#### Local

In [ ]:
print(data.speeds('local', 'train').shape)
print(data.speeds('local', 'test').shape)
print()
print(data.speeds('local', 'train').shape)
print(data.speeds('local', 'test').shape)

#### Full

In [5]:
print(data.speeds('full', 'train').shape)
print(data.speeds('full', 'test').shape)
print()
print(data.speeds('full', 'train').shape)
print(data.speeds('full', 'test').shape)

caching resources/dataset/preprocessed/full/train/speeds.csv.gz
(14321296, 9)
caching resources/dataset/preprocessed/full/test/speeds.csv.gz
(408824, 9)

(14321296, 9)
(408824, 9)

## Events

#### Originals

In [18]:
print(data.events_original('train').shape)
print(data.events_original('test').shape)
print()
print(data.events_original('train').shape)
print(data.events_original('test').shape)

caching resources/dataset/originals/events_train.csv.gz
(38008, 8)
caching resources/dataset/originals/events_test.csv.gz
(10468, 8)

(38008, 8)
(10468, 8)

#### Local

In [4]:
print(data.events('local', 'train').shape)
print(data.events('local', 'test').shape)
print()
print(data.events('local', 'train').shape)
print(data.events('local', 'test').shape)

caching resources/dataset/preprocessed/local/train/events.csv.gz
(2379725, 12)
caching resources/dataset/preprocessed/local/test/events.csv.gz
(676231, 12)

(2379725, 12)
(676231, 12)

#### Full

In [5]:
print(data.events('full', 'train').shape)
print(data.events('full', 'test').shape)
print()
print(data.events('full', 'train').shape)
print(data.events('full', 'test').shape)

caching resources/dataset/preprocessed/full/train/events.csv.gz

/Users/federico/miniconda3/envs/recsys/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

(3055962, 11)
caching resources/dataset/preprocessed/full/test/events.csv.gz
(444197, 11)

(3055962, 11)
(444197, 11)

## Sensors

#### Original

In [2]:
print(data.sensors_original().shape)
print()
print(data.sensors_original().shape)

caching resources/dataset/originals/sensors.csv.gz
(2269, 5)

(2269, 5)

#### Preprocessed

In [2]:
print(data.sensors().shape)
print()
print(data.sensors().shape)

caching resources/dataset/preprocessed/sensors.csv.gz
(2171, 5)

(2171, 5)

## Dataset

In [11]:
dataset_train = data.base_dataset('full','train')

caching resources/dataset/preprocessed/full/train/base_dataset.csv.gz

In [20]:
dataset[dataset_train.event_index == 38179]

/Users/federico/miniconda3/envs/recsys/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [event_index, KEY, KM, EMERGENCY_LANE, LANES, ROAD_TYPE, EVENT_DETAIL, EVENT_TYPE, DATETIME_UTC_-4, DATETIME_UTC_-3, DATETIME_UTC_-2, DATETIME_UTC_-1, DATETIME_UTC_y_0, DATETIME_UTC_y_1, DATETIME_UTC_y_2, DATETIME_UTC_y_3, SPEED_AVG_-4, SPEED_AVG_-3, SPEED_AVG_-2, SPEED_AVG_-1, SPEED_AVG_Y_0, SPEED_AVG_Y_1, SPEED_AVG_Y_2, SPEED_AVG_Y_3, SPEED_SD_-4, SPEED_SD_-3, SPEED_SD_-2, SPEED_SD_-1, SPEED_MAX_-4, SPEED_MAX_-3, SPEED_MAX_-2, SPEED_MAX_-1, SPEED_MIN_-4, SPEED_MIN_-3, SPEED_MIN_-2, SPEED_MIN_-1, N_VEHICLES_-4, N_VEHICLES_-3, N_VEHICLES_-2, N_VEHICLES_-1, WEATHER_-4, WEATHER_-3, WEATHER_-2, WEATHER_-1, DISTANCE_-4, DISTANCE_-3, DISTANCE_-2, DISTANCE_-1, TEMPERATURE_-4, TEMPERATURE_-3, TEMPERATURE_-2, TEMPERATURE_-1, MIN_TEMPERATURE_-4, MIN_TEMPERATURE_-3, MIN_TEMPERATURE_-2, MIN_TEMPERATURE_-1, MAX_TEMPERATURE_-4, MAX_TEMPERATURE_-3, MAX_TEMPERATURE_-2, MAX_TEMPERATURE_-1]
Index: []

In [2]:
dataset = data.base_dataset('full','test')

caching resources/dataset/preprocessed/full/test/base_dataset.csv.gz

In [3]:
dataset.shape

(5798, 60)

In [4]:
sum(np.all(dataset[['SPEED_AVG_-4','SPEED_AVG_-3','SPEED_AVG_-2','SPEED_AVG_-1']].notnull(), axis=1)*1)

394

In [5]:
dataset.head(10)

,event_index,KEY,KM,EMERGENCY_LANE,LANES,ROAD_TYPE,EVENT_DETAIL,EVENT_TYPE,DATETIME_UTC_-4,DATETIME_UTC_-3,DATETIME_UTC_-2,DATETIME_UTC_-1,DATETIME_UTC_y_0,DATETIME_UTC_y_1,DATETIME_UTC_y_2,DATETIME_UTC_y_3,SPEED_AVG_-4,SPEED_AVG_-3,SPEED_AVG_-2,SPEED_AVG_-1,SPEED_AVG_Y_0,SPEED_AVG_Y_1,SPEED_AVG_Y_2,SPEED_AVG_Y_3,SPEED_SD_-4,SPEED_SD_-3,SPEED_SD_-2,SPEED_SD_-1,SPEED_MAX_-4,SPEED_MAX_-3,SPEED_MAX_-2,SPEED_MAX_-1,SPEED_MIN_-4,SPEED_MIN_-3,SPEED_MIN_-2,SPEED_MIN_-1,N_VEHICLES_-4,N_VEHICLES_-3,N_VEHICLES_-2,N_VEHICLES_-1,WEATHER_-4,WEATHER_-3,WEATHER_-2,WEATHER_-1,DISTANCE_-4,DISTANCE_-3,DISTANCE_-2,DISTANCE_-1,TEMPERATURE_-4,TEMPERATURE_-3,TEMPERATURE_-2,TEMPERATURE_-1,MIN_TEMPERATURE_-4,MIN_TEMPERATURE_-3,MIN_TEMPERATURE_-2,MIN_TEMPERATURE_-1,MAX_TEMPERATURE_-4,MAX_TEMPERATURE_-3,MAX_TEMPERATURE_-2,MAX_TEMPERATURE_-1
0,0,146,997,0,1,0,15,Veicolo_in_avaria,2019-01-01 07:00:00,2019-01-01 07:15:00,2019-01-01 07:30:00,2019-01-01 07:45:00,2019-01-01 08:00:00,2019-01-01 08:15:00,2019-01-01 08:30:00,2019-01-01 08:45:00,153.059376,151.662442,146.585878,NaN,NaN,120.078239,118.481162,NaN,15.328561,16.581346,14.965800,NaN,203.868,195.778,203.868,NaN,85.754,82.518,79.282,NaN,189.0,226.0,263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,523,965,0,2,0,2,Ostacolo_in_carreggiata,2019-01-04 11:30:00,2019-01-04 11:45:00,2019-01-04 12:00:00,2019-01-04 12:15:00,2019-01-04 12:30:00,2019-01-04 12:45:00,2019-01-04 13:00:00,2019-01-04 13:15:00,228.083461,230.800631,232.734779,NaN,NaN,238.691959,236.901522,NaN,35.697199,29.476410,39.212064,NaN,406.118,334.926,326.836,NaN,74.428,165.036,66.338,NaN,178.0,206.0,195.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8,146,997,0,1,0,22,Veicolo_in_avaria,2019-01-04 11:30:00,2019-01-04 11:45:00,2019-01-04 12:00:00,2019-01-04 12:15:00,2019-01-04 12:30:00,2019-01-04 12:45:00,2019-01-04 13:00:00,2019-01-04 13:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,525,278,0,2,0,2,Ostacolo_in_carreggiata,2019-01-05 07:00:00,2019-01-05 07:15:00,2019-01-05 07:30:00,2019-01-05 07:45:00,2019-01-05 08:00:00,2019-01-05 08:15:00,2019-01-05 08:30:00,2019-01-05 08:45:00,229.191226,219.050436,220.973763,NaN,NaN,NaN,NaN,NaN,41.832668,33.935201,31.743712,NaN,406.118,351.106,328.454,NaN,166.654,74.428,74.428,NaN,106.0,133.0,194.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25,525,319,0,2,0,8,Segnaletica_orizzontale,2019-01-07 07:45:00,2019-01-07 08:00:00,2019-01-07 08:15:00,2019-01-07 08:30:00,2019-01-07 08:45:00,2019-01-07 09:00:00,2019-01-07 09:15:00,2019-01-07 09:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,30,517,728,0,2,0,32,Gestione_viabilita,2019-01-07 20:45:00,2019-01-07 21:00:00,2019-01-07 21:15:00,2019-01-07 21:30:00,2019-01-07 21:45:00,2019-01-07 22:00:00,2019-01-07 22:15:00,2019-01-07 22:30:00,234.867065,226.225818,233.281791,231.50344,NaN,NaN,NaN,NaN,36.644975,36.233708,29.830358,35.205016,333.308,325.218,302.566,343.016,69.574,74.428,169.890,163.418,107.0,99.0,67.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,60,146,919,0,1,0,31,Pavimentazione,2019-01-13 11:00:00,2019-01-13 11:15:00,2019-01-13 11:30:00,2019-01-13 11:45:00,2019-01-13 12:00:00,2019-01-13 12:15:00,2019-01-13 12:30:00,2019-01-13 12:45:00,167.678733,170.262283,172.267215,NaN,NaN,NaN,170.621952,NaN,13.677706,13.344137,11.448415,NaN,241.082,213.576,203.868,NaN,140.766,144.002,142.384,NaN,120.0,113.0,130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,60,146,925,0,2,0,31,Pavimentazione,2019-01-13 11:00:00,2019-01-13 11:15:00,2019-01-13 11:30:00,2019-01-13 11:45:00,2019-01-13 12:00:00,2019-01-13 12:15:00,2019-01-13 12:30:00,2019-01-13 12:45:00,155.180909,155.071175,157.984926,NaN,NaN,NaN,153.076870,NaN,19.055294,18.822371,18.141930,NaN,203.868,210.340,224.902,NaN,111.642,124.586,119.732,NaN,66.0,63.0,95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,60,146,939,0,1,0,31,Pavimentazione,2019-01-13 11:00:00,2019-01-13 11:15:00,2019-01-13 11:30:00,2019-01-13 11:45:00,2019-01-13 12:00:00,2019-01-13 12:15:00,2019-01-13 12:30:00,2019-01-13 12:45:00,170.885692,175.962045,180.683244,NaN,NaN,NaN,180.171042,NaN,20.526360,19.544708,20.441065,NaN,244.318,257.262,273.442,NaN,139.148,134.294,156.946,NaN,78.0,89.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,60,146,990,0,1,0,31,Pavimentazione,2019-01-13 11:00:00,2019-01-13 11:15:00,2019-01-13 11:30:00,2019-01-13 11:45:00,2019-01-13 12:00:00,2019-01-13 12:15:00,2019-01-13 12:30:00,2019-01-13 12:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
evfinal = data.events_original('test2')

caching resources/dataset/originals/events_2019.csv.gz

In [5]:
evfinal.loc[[60]]

NameError: name 'evfinal' is not defined

In [5]:
lorofile = pd.read_csv('resources/dataset/originals/speeds_evaluation__only_datetimes__2019.csv')
lorofile['DATETIME_UTC'] = pd.to_datetime(lorofile['DATETIME_UTC'])

In [6]:
print(lorofile.shape)
print('STEP 0', lorofile[lorofile.PREDICTION_STEP == 0].shape)
print('STEP 1', lorofile[lorofile.PREDICTION_STEP == 1].shape)
print('STEP 2', lorofile[lorofile.PREDICTION_STEP == 2].shape)
print('STEP 3', lorofile[lorofile.PREDICTION_STEP == 3].shape)

(1615, 4)
STEP 0 (428, 4)
STEP 1 (417, 4)
STEP 2 (392, 4)
STEP 3 (378, 4)

In [7]:
check_missing0 = lorofile[lorofile.PREDICTION_STEP == 0].merge(dataset[['KEY','KM','event_index','DATETIME_UTC_y_0']], how='left', \
                                              left_on=['KEY','KM','DATETIME_UTC'], right_on=['KEY','KM','DATETIME_UTC_y_0'])
check_missing1 = lorofile[lorofile.PREDICTION_STEP == 1].merge(dataset[['KEY','KM','event_index','DATETIME_UTC_y_1']], how='left', \
                                              left_on=['KEY','KM','DATETIME_UTC'], right_on=['KEY','KM','DATETIME_UTC_y_1'])
check_missing2 = lorofile[lorofile.PREDICTION_STEP == 2].merge(dataset[['KEY','KM','event_index','DATETIME_UTC_y_2']], how='left', \
                                              left_on=['KEY','KM','DATETIME_UTC'], right_on=['KEY','KM','DATETIME_UTC_y_2'])
check_missing3 = lorofile[lorofile.PREDICTION_STEP == 3].merge(dataset[['KEY','KM','event_index','DATETIME_UTC_y_3']], how='left', \
                                              left_on=['KEY','KM','DATETIME_UTC'], right_on=['KEY','KM','DATETIME_UTC_y_3'])

In [8]:
print('missing step 0:', sum(check_missing0.event_index.isnull()*1))
print('missing step 1:', sum(check_missing1.event_index.isnull()*1))
print('missing step 2:', sum(check_missing2.event_index.isnull()*1))
print('missing step 3:', sum(check_missing3.event_index.isnull()*1))

missing step 0: 0
missing step 1: 0
missing step 2: 0
missing step 3: 0

In [15]:
dataset[dataset.event_index == 12251]

,event_index,KEY,KM,EMERGENCY_LANE,LANES,ROAD_TYPE,EVENT_DETAIL,EVENT_TYPE,DATETIME_UTC_-4,DATETIME_UTC_-3,DATETIME_UTC_-2,DATETIME_UTC_-1,DATETIME_UTC_y_0,DATETIME_UTC_y_1,DATETIME_UTC_y_2,DATETIME_UTC_y_3,SPEED_AVG_-4,SPEED_AVG_-3,SPEED_AVG_-2,SPEED_AVG_-1,SPEED_AVG_Y_0,SPEED_AVG_Y_1,SPEED_AVG_Y_2,SPEED_AVG_Y_3,SPEED_SD_-4,SPEED_SD_-3,SPEED_SD_-2,SPEED_SD_-1,SPEED_MAX_-4,SPEED_MAX_-3,SPEED_MAX_-2,SPEED_MAX_-1,SPEED_MIN_-4,SPEED_MIN_-3,SPEED_MIN_-2,SPEED_MIN_-1,N_VEHICLES_-4,N_VEHICLES_-3,N_VEHICLES_-2,N_VEHICLES_-1,WEATHER_-4,WEATHER_-3,WEATHER_-2,WEATHER_-1,DISTANCE_-4,DISTANCE_-3,DISTANCE_-2,DISTANCE_-1,TEMPERATURE_-4,TEMPERATURE_-3,TEMPERATURE_-2,TEMPERATURE_-1,MIN_TEMPERATURE_-4,MIN_TEMPERATURE_-3,MIN_TEMPERATURE_-2,MIN_TEMPERATURE_-1,MAX_TEMPERATURE_-4,MAX_TEMPERATURE_-3,MAX_TEMPERATURE_-2,MAX_TEMPERATURE_-1
4499,12251,533,174,0,2,0,40,Segnaletica_verticale,2019-01-05 08:45:00,2019-01-05 09:00:00,2019-01-05 09:15:00,2019-01-05 09:30:00,2019-01-05 09:45:00,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,201.048057,NaN,NaN,NaN,NaN,NaN,NaN,217.351333,36.832043,NaN,NaN,NaN,271.824,NaN,NaN,NaN,63.102,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4500,12251,533,190,0,2,0,40,Segnaletica_verticale,2019-01-05 08:45:00,2019-01-05 09:00:00,2019-01-05 09:15:00,2019-01-05 09:30:00,2019-01-05 09:45:00,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4501,12251,533,194,0,2,0,40,Segnaletica_verticale,2019-01-05 08:45:00,2019-01-05 09:00:00,2019-01-05 09:15:00,2019-01-05 09:30:00,2019-01-05 09:45:00,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4502,12251,533,197,0,2,0,40,Segnaletica_verticale,2019-01-05 08:45:00,2019-01-05 09:00:00,2019-01-05 09:15:00,2019-01-05 09:30:00,2019-01-05 09:45:00,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4503,12251,533,205,0,1,0,40,Segnaletica_verticale,2019-01-05 08:45:00,2019-01-05 09:00:00,2019-01-05 09:15:00,2019-01-05 09:30:00,2019-01-05 09:45:00,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,132.239140,133.250617,133.493010,NaN,NaN,NaN,NaN,NaN,15.130819,12.727057,11.968003,NaN,182.834,182.834,169.890,NaN,108.406,110.024,98.698,NaN,100.0,107.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4504,12251,533,217,0,1,0,40,Segnaletica_verticale,2019-01-05 08:45:00,2019-01-05 09:00:00,2019-01-05 09:15:00,2019-01-05 09:30:00,2019-01-05 09:45:00,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,179.448185,185.703660,165.471615,NaN,NaN,NaN,NaN,NaN,17.968608,30.979592,32.228254,NaN,232.992,247.554,221.666,NaN,155.328,74.428,59.866,NaN,54.0,53.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4505,12251,533,231,0,1,0,40,Segnaletica_verticale,2019-01-05 08:45:00,2019-01-05 09:00:00,2019-01-05 09:15:00,2019-01-05 09:30:00,2019-01-05 09:45:00,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,143.132108,150.096467,149.893705,NaN,NaN,NaN,NaN,NaN,26.466703,12.632620,12.104574,NaN,181.216,199.014,182.834,NaN,63.102,122.968,124.586,NaN,279.0,240.0,237.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
events_test[(events_test.KEY == 533) & (events_test.START_DATETIME_UTC < '2019-01-05 09:30:00') & (events_test.START_DATETIME_UTC >= '2019-01-05 09:00:00')]

,START_DATETIME_UTC,END_DATETIME_UTC,EVENT_DETAIL,EVENT_TYPE,KM_END,KM_START,KEY,KEY_2
12251,2019-01-05 09:24:00,2019-01-05 14:03:00,40.0,Segnaletica_verticale,239,152,533,533_239

In [11]:
check_missing0[check_missing0.event_index.isnull()]

,KEY,KM,DATETIME_UTC,PREDICTION_STEP,event_index,DATETIME_UTC_y_0
0,533,231,2019-01-05 09:30:00,0,NaN,NaT
1,102,837,2019-01-05 08:15:00,0,NaN,NaT
2,4,176,2019-01-01 12:15:00,0,NaN,NaT
3,292,789,2019-01-09 13:00:00,0,NaN,NaT
5,46,483,2019-01-19 14:00:00,0,NaN,NaT
6,74,83,2019-01-01 08:00:00,0,NaN,NaT
7,537,303,2019-01-02 15:15:00,0,NaN,NaT
8,531,749,2019-01-01 08:00:00,0,NaN,NaT
9,46,432,2019-01-17 16:45:00,0,NaN,NaT
10,146,876,2019-01-25 08:45:00,0,NaN,NaT
11,4,232,2019-01-22 09:30:00,0,NaN,NaT
12,86,367,2019-01-03 21:15:00,0,NaN,NaT
13,556,533,2019-02-07 08:15:00,0,NaN,NaT
14,132,655,2019-01-06 22:15:00,0,NaN,NaT
15,226,808,2019-01-20 10:30:00,0,NaN,NaT
16,363,218,2019-01-13 03:00:00,0,NaN,NaT
17,491,219,2019-01-01 02:30:00,0,NaN,NaT
18,322,514,2019-01-18 04:45:00,0,NaN,NaT
19,566,116,2019-01-12 02:45:00,0,NaN,NaT
21,234,597,2019-01-07 09:30:00,0,NaN,NaT
22,4,203,2019-01-07 09:30:00,0,NaN,NaT
23,531,836,2019-01-06 08:15:00,0,NaN,NaT
24,326,301,2019-01-02 08:00:00,0,NaN,NaT
25,373,504,2019-01-05 07:45:00,0,NaN,NaT
26,525,278,2019-01-05 07:45:00,0,NaN,NaT
27,217,959,2019-02-03 08:30:00,0,NaN,NaT
28,16,588,2019-01-01 06:45:00,0,NaN,NaT
29,292,767,2019-01-01 06:15:00,0,NaN,NaT
30,86,370,2019-01-12 14:00:00,0,NaN,NaT
31,578,550,2019-01-04 08:00:00,0,NaN,NaT
...,...,...,...,...,...,...
394,219,73,2019-02-10 08:30:00,0,NaN,NaT
395,262,406,2019-01-21 12:00:00,0,NaN,NaT
396,533,205,2019-01-05 09:30:00,0,NaN,NaT
397,533,217,2019-01-05 09:30:00,0,NaN,NaT
398,467,882,2019-01-08 08:30:00,0,NaN,NaT
400,46,509,2019-01-01 12:30:00,0,NaN,NaT
401,504,586,2019-01-05 08:00:00,0,NaN,NaT
402,326,486,2019-01-01 09:15:00,0,NaN,NaT
403,16,555,2019-01-01 08:00:00,0,NaN,NaT
404,0,488,2019-01-01 08:45:00,0,NaN,NaT
405,397,498,2019-01-27 12:30:00,0,NaN,NaT
406,393,244,2019-01-17 13:30:00,0,NaN,NaT
407,0,411,2019-01-01 19:45:00,0,NaN,NaT
408,421,610,2019-02-11 08:00:00,0,NaN,NaT
409,46,387,2019-01-24 12:15:00,0,NaN,NaT
410,272,65,2019-01-12 20:30:00,0,NaN,NaT
411,86,353,2019-01-03 21:15:00,0,NaN,NaT
413,226,818,2019-01-08 22:00:00,0,NaN,NaT
414,116,241,2019-01-14 12:00:00,0,NaN,NaT
415,574,347,2019-01-14 22:45:00,0,NaN,NaT
416,419,394,2019-01-05 05:15:00,0,NaN,NaT
417,213,547,2019-01-06 02:00:00,0,NaN,NaT
418,6,675,2019-01-06 16:15:00,0,NaN,NaT
419,114,327,2019-01-06 08:00:00,0,NaN,NaT
420,403,611,2019-02-05 12:30:00,0,NaN,NaT
422,375,914,2019-01-04 07:00:00,0,NaN,NaT
423,118,488,2019-01-28 11:00:00,0,NaN,NaT
424,467,734,2019-02-12 08:45:00,0,NaN,NaT
426,431,750,2019-01-02 07:45:00,0,NaN,NaT
427,184,365,2019-02-04 07:00:00,0,NaN,NaT

In [11]:
#dataset[(dataset.KEY == 566) & (dataset.KM == 116)]
dataset[(dataset.KEY == 566)]

,KEY,KM,event_index,EMERGENCY_LANE,LANES,ROAD_TYPE,EVENT_DETAIL,EVENT_TYPE,DATETIME_UTC_-4,DATETIME_UTC_-3,DATETIME_UTC_-2,DATETIME_UTC_-1,DATETIME_UTC_y_0,DATETIME_UTC_y_1,DATETIME_UTC_y_2,DATETIME_UTC_y_3,SPEED_AVG_-4,SPEED_AVG_-3,SPEED_AVG_-2,SPEED_AVG_-1,SPEED_AVG_Y_0,SPEED_AVG_Y_1,SPEED_AVG_Y_2,SPEED_AVG_Y_3,SPEED_SD_-4,SPEED_SD_-3,SPEED_SD_-2,SPEED_SD_-1,SPEED_MAX_-4,SPEED_MAX_-3,SPEED_MAX_-2,SPEED_MAX_-1,SPEED_MIN_-4,SPEED_MIN_-3,SPEED_MIN_-2,SPEED_MIN_-1,N_VEHICLES_-4,N_VEHICLES_-3,N_VEHICLES_-2,N_VEHICLES_-1,WEATHER_-4,WEATHER_-3,WEATHER_-2,WEATHER_-1,DISTANCE_-4,DISTANCE_-3,DISTANCE_-2,DISTANCE_-1,TEMPERATURE_-4,TEMPERATURE_-3,TEMPERATURE_-2,TEMPERATURE_-1,MIN_TEMPERATURE_-4,MIN_TEMPERATURE_-3,MIN_TEMPERATURE_-2,MIN_TEMPERATURE_-1,MAX_TEMPERATURE_-4,MAX_TEMPERATURE_-3,MAX_TEMPERATURE_-2,MAX_TEMPERATURE_-1
421,566,116,12822,0,1,0,1,Meteo,2019-01-12 01:45:00,2019-01-12 02:00:00,2019-01-12 02:15:00,2019-01-12 02:30:00,2019-01-12 02:45:00,2019-01-12 03:00:00,2019-01-12 03:15:00,2019-01-12 03:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422,566,171,12798,0,1,0,37,Regimazione_delle_acque,2019-01-05 10:00:00,2019-01-05 10:15:00,2019-01-05 10:30:00,2019-01-05 10:45:00,2019-01-05 11:00:00,2019-01-05 11:15:00,2019-01-05 11:30:00,2019-01-05 11:45:00,NaN,NaN,NaN,NaN,139.957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
423,566,171,12853,0,1,0,28,Pavimentazione,2019-01-21 07:15:00,2019-01-21 07:30:00,2019-01-21 07:45:00,2019-01-21 08:00:00,2019-01-21 08:15:00,2019-01-21 08:30:00,2019-01-21 08:45:00,2019-01-21 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#speeds_test = data.speeds('full','test')
events_test = data.events_original('test2')

In [19]:
e = data.events('full','test')

caching resources/dataset/preprocessed/full/test/events.csv.gz

In [21]:
e[e['index'] == 5265]

,index,START_DATETIME_UTC,END_DATETIME_UTC,EVENT_DETAIL,EVENT_TYPE,KM_END,KM_START,KEY,KEY_2,KM_EVENT,step_duration,DATETIME_UTC
127780,5265,2019-01-12 16:00:00,2019-01-12 17:15:00,6.0,extended_accident,308,304,537,537_306,306.0,6,2019-01-12 16:00:00
127781,5265,2019-01-12 16:00:00,2019-01-12 17:15:00,6.0,extended_accident,308,304,537,537_306,306.0,6,2019-01-12 16:15:00
127782,5265,2019-01-12 16:00:00,2019-01-12 17:15:00,6.0,extended_accident,308,304,537,537_306,306.0,6,2019-01-12 16:30:00
127783,5265,2019-01-12 16:00:00,2019-01-12 17:15:00,6.0,extended_accident,308,304,537,537_306,306.0,6,2019-01-12 16:45:00
127784,5265,2019-01-12 16:00:00,2019-01-12 17:15:00,6.0,extended_accident,308,304,537,537_306,306.0,6,2019-01-12 17:00:00
127785,5265,2019-01-12 16:00:00,2019-01-12 17:15:00,6.0,extended_accident,308,304,537,537_306,306.0,6,2019-01-12 17:15:00